### ISSUE TITLE
Only resnet and vgg are available for BNN

### ISSUE THREAD

**Issue by huizhg** [kartikgupta-at-anu/attack-bnn#2]
Hi, I noticed that there are only two architectures (and weights) of BNN (resnet and vgg) are available. Could you provide the architectures of the remaining BNN models (resnet-50, densenet121, mobilenet). Thanks.

**Comment by kartikgupta-at-anu** [comment]
I do not have access to models anymore as I have left my previous organization but you can train the other BNN models using our other MD repo.
