### ISSUE TITLE
Problems when re-implementing white-box attack experiments on BNNs

### ISSUE THREAD

**Issue by yyl-github-1896** [kartikgupta-at-anu/attack-bnn#2]
Hi, I am very interested in the gradient masking problem reported in your paper, as well as your methods for fixing it. But when I tired to re-implement the experiments which is corresponding to the Table 1 in your paper, I found that the adversarial accuracy is much lower than that in the Tabel 1. I obtained adversarial accuarcy of 0.02% on ResNet18 and 27.44% on VGG16 (the numbers reported in Tabel 1 are 8.57% and 78.01, respectively). 

I am sure that I followed your experimental settings. I used a non-official re-implementation (https://github.com/itayhubara/BinaryNet.pytorch) in PyTorch to train my BNNs. My BNN clean acc on ResNet18 and VGG16 are 88.29% and 90.27%, respectively. I have checked that the weights and activations of my BNNs are binarized correctly. So I wonder that is there any difference on BNN re-implementation between yours and mine?

**Comment by yyl-github-1896** [comment]
I found that the vgg structure in (https://github.com/itayhubara/BinaryNet.pytorch) is not exactly vgg16, and in this bnn implamentation, network modules are inflated to improve accuracy. Anyway, I'm still working on these problems.

**Comment by kartikgupta-at-anu** [comment]
It depends on how the network has been binarized. It is possible that first and last layers are not quantized. In our experiments, we quantize all parameters as well BN and bias layers.
